### ISSUE TITLE
Filter out pull requests

### ISSUE THREAD

**Issue by jayvdb** [bekicot/gsoc-prep-tasks#1]
https://bekicot.github.io/gsoc-prep-tasks/#/issues?q=coala has lots of pull requests

Even merged PRs like https://github.com/coala/projects/pull/281

**Comment by bekicot** [comment]
Fixed in https://github.com/bekicot/gsoc-prep-tasks/commit/c9d1930bee224280f3f3247fca38e2c6906c1bcf
