### ISSUE TITLE
Strip <!-- ... --> from issue body

### ISSUE THREAD

**Issue by jayvdb** [bekicot/gsoc-prep-tasks#3]
A common trick for issue template is to use html comments so they dont appear on save. e.g. https://github.com/coala/coala/blob/master/ISSUE_TEMPLATE is:

```html
<!-- Hello! If you're filing a bug, please include every step so as to help us reproduce it on our machines. If you're unsure about how to file an issue, use the issue template. If you need any help regarding usage of coala, check out the documentation or hit us up on chat. You can ignore or delete this text, it is commented and won't appear when the issue is submitted or previewed.

Chat: https://coala.io/chat
Issue Template: https://github.com/coala/coala/blob/master/CONTRIBUTING.rst#filing-issues
Documentation: https://docs.coala.io
-->
```

This comment leaks into the issue descriptions on this website.

see https://bekicot.github.io/gsoc-prep-tasks/#/issues?q=coala

This is a simplified version of https://github.com/bekicot/gsoc-prep-tasks/issues/2

**Comment by bekicot** [comment]
@jayvdb Fixed in #42e562a along with #2
