### ISSUE TITLE
Group tasks by org

### ISSUE THREAD

**Issue by jayvdb** [bekicot/gsoc-prep-tasks#4]
Most GSOC orgs will have many repos, under the main org, and then other repos outside the org which appear under keyword searches.

It would be very useful to group all tasks by org, and search on org name should place that group at the top.

e.g. https://bekicot.github.io/gsoc-prep-tasks/#/issues?q=opensuse should have an 'opensuse' group at the top.
And then lots of other opensuse related projects after that.

**Comment by bekicot** [comment]
@jayvdb 
Thanks for the feature request.
I've added https://github.com/bekicot/gsoc-prep-tasks/commit/8ffe743a0cd46b265696c94feed39e8e67144987 for group by repository name.

**Comment by jayvdb** [comment]
Ok, lots of lovely UI improvements there.
But, we still need "group by repository user", so that all of the issues in any of the `coala` repositories are grouped together.

**Comment by jayvdb** [comment]
Looks great!
