### ISSUE TITLE
Add a easy selector for GSOC org

### ISSUE THREAD

**Issue by jayvdb** [bekicot/gsoc-prep-tasks#6]
Ideally a user can pick a GSOC org easily.

i.e. selecting 'discourse' in a menu should take the user immediately to a prettier version of https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+user%3Adiscourse

It could be a JSON file which populates a menu list, prefilled with a few of the GSOC orgs, and then other contributors can do PRs to add extra orgs .

**Comment by bekicot** [comment]
Fixed in https://github.com/bekicot/gsoc-prep-tasks/commit/8e53d3a980db6cac0c596df99ddc26e71f429d6b . 
It is look ugly now. But after we have 5+ Orgs there, it will looks beter.
